backend:
  backend:
  name: github
  repo: InfiniBuilds/thing2   # YOUR_GITHUB_USERNAME/REPO_NAME
  branch: main

oauth:
  client_id: Ov23liZJjLvvkGfBWfwh
  

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    format: "mdx"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
